import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/custom/Header";
import Footer from '../components/custom/Footer'
import '@fontsource-variable/inter';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "juanigarciadev's portfolio",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="font-serif font-light bg-main text-white overflow-x-hidden">
                <Header />
                {children}
                <Footer/>
            </body>
        </html>
    );
}
